### ISSUE TITLE
cadê os créditos?

### ISSUE THREAD

**Issue by DerpyXD** [MrGamingBR/Zoe#4]
você copia o repositório do cara e nem deixa os créditos? complicado assim, vou deixar o link aqui pra te ajudar a dar os créditos pro autor

https://github.com/Gorillas-Team/Codya

**Comment by MrGamingBR** [comment]
Primeiro, Não copiei de forma alguma. Vocês oferecem um Template para bot e reclamam depois de ver que um bot está crescendo absurdamente e usa o template que vocês próprios ofereceram. Não irei dar crédito para Codya mas vou dar pelo Boiterplate. Tenha uma boa noite

**Comment by DerpyXD** [comment]
> Primeiro, Não copiei de forma alguma. Vocês oferecem um Template para bot e reclamam depois de ver que um bot está crescendo absurdamente e usa o template que vocês próprios ofereceram. Não irei dar crédito para Codya mas vou dar pelo Boiterplate. Tenha uma boa noite

eu não estou reclamando, quero saber onde está os créditos do cara que fez o que você está usando

**Comment by MrGamingBR** [comment]
Engraçado que só vieram pedir isso agora sendo que tem 1 mes e pouco que uso o Template. Enfim, Espero nunca mais ter que responde-los ou ver Issues criadas por Vocês. 
Tenham uma Boa Noite.

**Comment by zMigueel** [comment]
> Engraçado que só vieram pedir isso agora sendo que tem 1 mes e pouco que uso o Template. Enfim, Espero nunca mais ter que responde-los ou ver Issues criadas por Vocês.
> Tenham uma Boa Noite.

Engraçado que tu me pede ajuda o dia todo e quer reclamar, e ainda roubou os códigos, deu desculpa que o negócio era open source e ainda acha que tem direito de falar algo.
Passar bem. 🤙

**Comment by MrGamingBR** [comment]
Só pra não deixar isso como se eu "arreguei", Eu peguei a estrutura de vocês certo ? Sim. Vocês falam de mim como se sei lá, Eu posso ter roubado o código de vocês mas e o Gorilink ? Aquela copia barata do erela.js. Vocês podem literalmente fazer um Wrapper igual a outro e não acontecer nada e eu não posso pegar um Código que vocês disponibilizaram como Template ? Que hipocrisia amigos, Vocês me irritaram pra caramba com esse bagulho de fazer a Codya ganhar em cima disso e tudo e juntamente abrindo Issue e PR em plena meia noite e ainda vem me mandar o Link do Issue e do PR na minha dm como se eu tivesse obrigação de responde-los na hora que querem. Boa noite.
